Feature/dev pqnv 40
ElwinghL/kinenveut pull request #5
Opened 2020-09-26 17:07 UTC by bchanez

2020-09-26 19:27 UTC, OphelieTrd approved these changes

2020-09-27 10:08 UTC, ElwinghL commented
Normalement on évite de mettre les .lock sur le dépot. C'est généré par machine en fonction des versions de node et de composer

2020-09-27 10:08 UTC, ElwinghL requested changes
Ajouter les .lock au gitignore

2020-09-27 11:26 UTC, bchanez commented
Le fichier composer.lock contient la versionb
de nos dépendances au moment où l'on travaille sur le projet, du coup ça permet de voir des changements de version des dépendances plus facilement.

Pour moi il faut le versionner

2020-09-28 07:38 UTC, merged