Dev user management
ElwinghL/kinenveut pull request #58
Opened 2020-10-06 15:26 UTC by Riddsaw

2020-10-06 15:29 UTC, bchanez requested changes
try catch pour les requêtes svp ;)

2020-10-06 15:42 UTC, OphelieTrd submitted a review, later dismissed
Il manque les tests associés aux nouvelles fonctions sinon tip top, hâte de tester 👍

2020-10-06 21:39 UTC, bchanez approved these changes, later dismissed

2020-10-07 23:11 UTC, bchanez approved these changes

2020-10-07 23:11 UTC, merged